name: ci

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: invisirisk/pse-action@feature/intermediate-deno-rust-ca-devtest
        with:
          api_url: "https://app.stage.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY }}
          pse_image_tag: "dev-test"
          debug: true
      # ============= InvisiRisk Setup End =============
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno (canary)
        uses: denoland/setup-deno@v2
        with:
          deno-version: canary

      # ✅ "INSTALL PACKAGES" STEP (Deno equivalent)
      - name: Cache Deno deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/deno
          key: deno-${{ hashFiles('deno.lock') }}

      - name: Install / Pre-fetch dependencies
        run: deno cache deno.json

      - name: Lint
        run: deno lint

      # ============= InvisiRisk Cleanup =============
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@feature/intermediate-deno-rust-ca-devtest
        with:
          api_url: "https://app.stage.invisirisk.com"
          cleanup: "true"
      # ============= InvisiRisk Cleanup End =============
